DEPTH = ..
SUBDIR = ./game

include $(DEPTH)/Makefile.os

DIRECTORIES = gameplay_actions

include Makefile.objects

.PHONY: all
all : objects directories


include $(DEPTH)/Makefile.rules
include $(DEPTH)/Makefile.subdir
