DEPTH = ../..
SUBDIR = ./network/gnet

include $(DEPTH)/Makefile.os

include Makefile.objects

INCLUDE += $(INCLUDE_NETWORK)
LIBS += $(LIBS_NETWORK)

.PHONY: all
all : objects


include $(DEPTH)/Makefile.rules
include $(DEPTH)/Makefile.subdir
