FILE(READ ${infile} f0)
STRING( REGEX REPLACE "standard.defensive" "novice" f1 "${f0}" )
STRING( REGEX REPLACE "(type *= *[0-9]*:)[^\\]*" "\\1 monte carlo - jab or serve" f1 "${f1}" )
STRING( REGEX REPLACE "(future limit *= *[0-9]*:)[^\\]*" "\\1 1200" f1 "${f1}" )
STRING( REGEX REPLACE "(rating *= *[0-9]*:)[^\\]*" "\\1 average" f1 "${f1}" )
STRING( REGEX REPLACE "(trusting *=)[^\\]*" "\\1 true" f1 "${f1}" )
STRING( REGEX REPLACE "(remember tricks *=)[^\\]*" "\\1 6" f1 "${f1}" )
STRING( REGEX REPLACE "(last fehlcreation *=)[^\\]*" "\\1 6" f1 "${f1}" )
STRING( REGEX REPLACE "(first trick for trump points optimization *=)[^\\]*" "\\1 5" f1 "${f1}" )
STRING( REGEX REPLACE "(announce limit reply *=)[^\\]*" "\\1 12" f1 "${f1}" )
STRING( REGEX REPLACE "(take poverty *=)[^\\]*" "\\1 12" f1 "${f1}" )
FILE(WRITE ${outfile} "${f1}")
