FILE(READ ${infile} f0)
STRING( REGEX REPLACE "standard.defensive" "profi" f1 "${f0}" )
STRING( REGEX REPLACE "(type *= *(8|9|10|11)*:)[^\\]*" "\\1 gametree for team" f1 "${f1}" )
STRING( REGEX REPLACE "(rating *= *[0-9]*:)[^\\]*" "\\1 linear" f1 "${f1}" )
#STRING( REGEX REPLACE "(trusting *=)[^\\]*" "\\1 false" f1 "${f1}" )
STRING( REGEX REPLACE "(first card fehl creation *=)[^\\]*" "\\1 false" f1 "${f1}" )
STRING( REGEX REPLACE "(remember tricks *=)[^\\]*" "\\1 12" f1 "${f1}" )
STRING( REGEX REPLACE "(\nlimit queen *=)[^\\]*" "\\1 10" f1 "${f1}" )
STRING( REGEX REPLACE "(limit dolle *=)[^\\]*" "\\1 19" f1 "${f1}" )
STRING( REGEX REPLACE "(last fehlcreation *=)[^\\]*" "\\1 4" f1 "${f1}" )
STRING( REGEX REPLACE "(first trick for trump points optimization *=)[^\\]*" "\\1 5" f1 "${f1}" )
STRING( REGEX REPLACE "(announce limit *=)[^\\]*" "\\1 11" f1 "${f1}" )
STRING( REGEX REPLACE "(announce limit reply *=)[^\\]*" "\\1 10" f1 "${f1}" )
STRING( REGEX REPLACE "(take poverty *=)[^\\]*" "\\1 13" f1 "${f1}" )
STRING( REGEX REPLACE "(handvalue single solo =) [^\\]*" "\\1 18" f1 "${f1}" )
STRING( REGEX REPLACE "(handvalue double solo =) [^\\]*" "\\1 50" f1 "${f1}" )
STRING( REGEX REPLACE "(handvalue trible solo =) [^\\]*" "\\1 100" f1 "${f1}" )
STRING( REGEX REPLACE "(handvalue color solo =) [^\\]*" "\\1 28" f1 "${f1}" )
STRING( REGEX REPLACE "(handvalue meatless =) [^\\]*" "\\1 26" f1 "${f1}" )
FILE(WRITE ${outfile} "${f1}")
